# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
